import os
import re
import textwrap

from deploy_manager.config.settings import (
    NGINX_RATE_LIMIT_BURST,
    NGINX_RATE_LIMIT_RATE,
    NGINX_RATE_LIMIT_ZONE,
    NGINX_SITES_AVAILABLE,
    NGINX_SITES_ENABLED,
    REACT_BUILD_OUTPUT_CANDIDATES,
)
from deploy_manager.core.exceptions import DeployError
from deploy_manager.core.utils import confirm, run_cmd, ts_iso
from deploy_manager.projects.helpers import get_dest_dir


def _nginx_is_installed():
    return run_cmd(["which", "nginx"], check=False, capture=True).returncode == 0


def _certbot_is_installed():
    return run_cmd(["which", "certbot"], check=False, capture=True).returncode == 0


def _ensure_nginx_rate_limit_zone():
    snippet = "/etc/nginx/conf.d/deploy-rate-limit.conf"
    if os.path.isfile(snippet):
        with open(snippet) as f:
            if NGINX_RATE_LIMIT_ZONE in f.read():
                return
    os.makedirs(os.path.dirname(snippet), exist_ok=True)
    with open(snippet, "w") as f:
        f.write(f"# Auto-generated by Deploy Manager\n"
                f"limit_req_zone $binary_remote_addr zone={NGINX_RATE_LIMIT_ZONE}:10m rate={NGINX_RATE_LIMIT_RATE};\n")


def generate_nginx_proxy_config(domain, port, project_name):
    return textwrap.dedent(f"""\
        # {project_name} — {domain} → 127.0.0.1:{port}
        # Generated: {ts_iso()}

        server {{
            server_name {domain};
            client_max_body_size 50m;

            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header Referrer-Policy "strict-origin-when-cross-origin" always;

            limit_req zone={NGINX_RATE_LIMIT_ZONE} burst={NGINX_RATE_LIMIT_BURST} nodelay;
            limit_req_status 429;

            gzip on;
            gzip_vary on;
            gzip_proxied any;
            gzip_comp_level 6;
            gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;

            location /.well-known/acme-challenge/ {{
                root /var/www/html;
            }}

            location / {{
                proxy_pass http://127.0.0.1:{port};
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }}

            listen 80;
            listen [::]:80;
        }}

        server {{
            if ($host = {domain}) {{
                return 301 https://$host$request_uri;
            }}

            listen 80;
            listen [::]:80;
            server_name {domain};
            return 404;
        }}
    """)


def generate_nginx_static_config(domain, project_name, static_root):
    return textwrap.dedent(f"""\
        # {project_name} static
        # {domain} → {static_root}  |  Generated: {ts_iso()}

        server {{
            listen 80;
            listen [::]:80;
            server_name {domain};

            root {static_root};
            index index.html;

            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header Referrer-Policy "strict-origin-when-cross-origin" always;

            limit_req zone={NGINX_RATE_LIMIT_ZONE} burst={NGINX_RATE_LIMIT_BURST} nodelay;
            limit_req_status 429;

            gzip on;
            gzip_vary on;
            gzip_proxied any;
            gzip_comp_level 6;
            gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;

                    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {{
                expires 1y;
                add_header Cache-Control "public, immutable";
                access_log off;
            }}

                    location / {{
                try_files $uri $uri/ /index.html;
            }}

            location /nginx-health {{
                access_log off;
                return 200 "ok";
                add_header Content-Type text/plain;
            }}

            location ~ /\\. {{
                deny all;
                access_log off;
                log_not_found off;
            }}
        }}
    """)


def create_nginx_config(proj, interactive=True):
    if not _nginx_is_installed():
        raise DeployError("nginx not installed. Install: apt install nginx")
    domain = proj.get("domain", "")
    port = proj.get("port", 3000)
    enable_ssl = proj.get("ssl", True)
    ptype = proj["type"]

    if interactive:
        print(f"\n  Nginx config for {proj['name']} ({ptype})")
        domain_input = input(f"  Domain [{domain or 'example.com'}]: ").strip()
        if domain_input:
            domain = domain_input
        if not domain:
            raise DeployError("No domain specified")
        if ptype != "react":
            port_input = input(f"  Backend port [{port}]: ").strip()
            if port_input.isdigit():
                port = int(port_input)
        enable_ssl = confirm("  Set up SSL with certbot?", default=enable_ssl)

    if not domain:
        raise DeployError("No domain configured. Set 'domain' in PROJECTS config.")
    if not re.match(r"^[a-zA-Z0-9][a-zA-Z0-9\-\.]*[a-zA-Z0-9]$", domain):
        raise DeployError(f"Invalid domain format: {domain}")

    if ptype == "react":
        dest_dir = get_dest_dir(proj)
        build_output = proj.get("build_output", REACT_BUILD_OUTPUT_CANDIDATES[0])
        for candidate in [build_output] + REACT_BUILD_OUTPUT_CANDIDATES:
            candidate_path = os.path.join(dest_dir, candidate)
            if os.path.isdir(candidate_path):
                build_output = candidate
                break
        static_root = os.path.join(dest_dir, build_output)
        config_content = generate_nginx_static_config(domain, proj["name"], static_root)
    else:
        config_content = generate_nginx_proxy_config(domain, port, proj["name"])

    _ensure_nginx_rate_limit_zone()

    config_name = re.sub(r"[^a-zA-Z0-9_\-]", "_", proj["name"])
    available_path = os.path.join(NGINX_SITES_AVAILABLE, config_name)
    enabled_path = os.path.join(NGINX_SITES_ENABLED, config_name)

    if os.path.isfile(available_path) and interactive:
        if not confirm(f"  {available_path} exists. Overwrite?"):
            return

    os.makedirs(NGINX_SITES_AVAILABLE, exist_ok=True)
    os.makedirs(NGINX_SITES_ENABLED, exist_ok=True)
    with open(available_path, "w") as f:
        f.write(config_content)
    if os.path.islink(enabled_path) or os.path.exists(enabled_path):
        os.remove(enabled_path)
    os.symlink(available_path, enabled_path)

    nginx_reload()

    if enable_ssl and _certbot_is_installed():
        if not interactive or confirm(f"  Run certbot for {domain}?", default=True):
            try:
                run_cmd(["certbot", "--nginx", "-d", domain, "--non-interactive",
                         "--agree-tos", "--redirect"], timeout=120)
            except DeployError as e:
                print(f"Certbot failed: {e}")
    elif enable_ssl:
        print(f"certbot not installed. Run: certbot --nginx -d {domain}")


def nginx_reload():
    result = run_cmd(["nginx", "-t"], check=False, capture=True)
    if result.returncode != 0:
        raise DeployError(f"nginx config test failed:\n{(result.stderr or '') + (result.stdout or '')}")
    run_cmd(["systemctl", "reload", "nginx"])


def remove_nginx_config(proj):
    config_name = re.sub(r"[^a-zA-Z0-9_\-]", "_", proj["name"])
    removed = False
    for path in [os.path.join(NGINX_SITES_ENABLED, config_name), os.path.join(NGINX_SITES_AVAILABLE, config_name)]:
        if os.path.islink(path) or os.path.exists(path):
            os.remove(path)
            removed = True
    if removed:
        nginx_reload()
